server:
  port: 8761
spring:
  application:
    name: Eureka-server
  # disable the cloud config at beginning
  cloud:
    config:
      enabled: false
# eureka configuration not register microservices by default false
eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
  server:
    waitTimeInMsWhenSyncEmpty: 0
  instance:
    hostname: localhost